// <auto-generated />
using System;
using ContactsApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactsApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ContactsApp.Models.Contact", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("extension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("ContactsApp.Models.RefreshToken", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("expiry")
                        .HasColumnType("TEXT");

                    b.Property<bool>("revoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("userid")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("ContactsApp.Models.User", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("contact_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("contactid")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("role")
                        .HasColumnType("TEXT");

                    b.Property<string>("salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("contactid");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ContactsApp.Models.RefreshToken", b =>
                {
                    b.HasOne("ContactsApp.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userid");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ContactsApp.Models.User", b =>
                {
                    b.HasOne("ContactsApp.Models.Contact", "contact")
                        .WithMany()
                        .HasForeignKey("contactid");

                    b.Navigation("contact");
                });
#pragma warning restore 612, 618
        }
    }
}
